---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deloitte-drifters-frontend
  namespace: qa
  labels:
    app: deloitte-drifters-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deloitte-drifters-frontend
  template:
    metadata:
      labels:
        app: deloitte-drifters-frontend
    spec:
      containers:
      - name: deloitte-drifters-frontend
        image: bhavgandhi/myexternal:v2
        env:
        - name: PORT
          value: "80"
        - name: SERVER
          value: "http://deloitte-drifters-backend-service"
        ports:
        - containerPort: 8082
          name: "events-port"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: deloitte-drifters-frontend-service
  namespace: qa
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 8080
  selector: 
    app: deloitte-drifters-frontend
  type: LoadBalancer

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: deloitte-drifters-frontend-autoscaler
  namespace: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: deloitte-drifters-frontend
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60