---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deloitte-drifters-backend
  namespace: dd-all
  labels:
    app: deloitte-drifters-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deloitte-drifters-backend
  template:
    metadata:
      labels:
        app: deloitte-drifters-backend
    spec:
      containers:
      - name: deloitte-drifters-backend
        image: bhavgandhi/myinternal:v2
        env:
        - name: PORT
          value: "8082"
        ports:
        - containerPort: 8082
          name: "events-port"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: deloitte-drifters-backend-service
  namespace: dd-all
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 8082
  selector: 
    app: deloitte-drifters-backend
  type: ClusterIP