name: Print PR Details to CSV
on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  Dev_Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print PR Message
        id: fetchTitle
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_message=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r '.head.commit.message')
          echo "::set-output name=pr_message::$pr_message"
          echo "PR Title: ${{ github.event.pull_request.title }}" 
          echo "PR Number: ${{ github.event.pull_request.number }}" 

          jiraID=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'IQE-[0-9]+')
          echo "::set-output name=jiraID::$jiraID"
          echo "Extracted IQE Text: $jiraID"

      - name: Print PR Head Message
        run: |
          echo "PR Head Message: ${{ steps.pr.outputs.pr_message }}"
      - name: executing Qtest
        run: |
          json_response=$(curl --location --request GET 'https://touchlessreg.qtestnet.com/api/v3/projects/8101/requirements/trace-matrix-report' --header 'Authorization: Bearer acbd5ab9-23c4-431f-b9e4-1dc7e63edc2f')
          jiraID=${{ steps.fetchTitle.outputs.jiraID }}
          echo "Extracted IQE Text: $jiraID"
          testcases=$(echo "$json_response" | jq '.[].requirements[] | select(.name | contains("IQE-9")) | select(.testcases).testcases')
          echo $testcases

      - name: Triggering api call
        run: |
          curl -d '{ "name": "TC-1, TC-2" }'  -H "Content-Type: application/json"  https://enl82rxlzwxt8.x.pipedream.net/
